[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [{ name = "Abi Raja", email = "abimanyuraja@gmail.com" }]
license = "MIT"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi==0.115.6",
    "uvicorn==0.25.0",
    "websockets==14.1",
    "openai==2.16.0",
    "python-dotenv==1.0.1",
    "beautifulsoup4==4.12.3",
    "httpx==0.28.1",
    "anthropic==0.84.0",
    "moviepy==1.0.3",
    "pillow==10.4.0",
    "aiohttp==3.11.11",
    "pydantic==2.10.4",
    "google-genai==1.60.0",
    "langfuse==3.0.2",
    "playwright==1.61.0",
    "pillow-heif==0.18.0",
]

[dependency-groups]
dev = [
    "pre-commit==3.8.0",
    "types-pillow==10.2.0.20240822",
    "pytest==7.4.4",
    "pyright==1.1.408",
    "pytest-asyncio==0.21.2",
]

[tool.poetry]
package-mode = false

[tool.uv]
package = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
